foodadvisor/config/routes.rb
Rails.application.routes.draw do
    
    get 'user_notifications/index'
    get 'preferiti/show'
    get 'user_profile/edit'
    get 'user_profile/show'
    put 'user_profile/update'
    get 'admin_profile/edit'
    get 'admin_profile/show'
    get 'profile/show'
    get 'critic_profile/show'
    get 'critic_profile/edit'
    put 'critic_profile/update'
    get 'competizione/index'
    get 'support/index'
    
    # rotta per la pagina principale
    root 'home#index'
    get 'root', to: 'home#index' 

    #caalback fb
    post 'auth/facebook/callback', to: 'sessions#facebook'
  
    # Defines the root path route ("/")
    # root "posts#index"

    # config/routes.rb
  resources :favorites, only: [] do
    delete :remove_rest_from_favorites, on: :collection
  end

  # config/routes.rb
  resources :favorites, only: [] do
    delete :remove_recipe_from_favorites, on: :collection
  end


  
    get 'classifiche', to: 'classifiche#index'
    get 'supporto', to: 'supporto#index'

    get 'about', to: 'about#index'

    
    resources :problems do
      member do
        put 'aggiorna_stato_problema', to: 'problems#aggiorna_stato_problema'
      end
    end

    resources :notifications, only: [:new, :create]
    resources :user_notifications, only: [:index]

    post 'restaurateur_profiles/update_pin', to: 'restaurateur_profiles#update_pin', as: 'update_pin_restaurateur_profile'
    
    # grafico
    get 'bookings_per_week', to: 'info#bookings_per_week'
    get 'daily_bookings_and_events', to: 'info#daily_bookings_and_events'

    # grafici personali
    get 'daily_bookings', to: 'critic_profile#daily_bookings'
    get 'monthly_bookings', to: 'critic_profile#monthly_bookings'
    get 'daily_bookings_user', to: 'user_profile#daily_bookings_user'
    get 'monthly_bookings_user', to: 'user_profile#monthly_bookings_user'
  
    #
    # Rotta per il form di login (GET e POST)
    get 'login', to: 'sessions#new'
  
    get '/registration/user', to: 'registration#new_user', as: 'new_user_registration'
    post '/registration/user', to: 'registration#create_user', as: 'create_user_registration'
  
    get '/registration/critico', to: 'registration#new_critico', as: 'new_critico_registration'
    post '/registration/critico', to: 'registration#create_critico', as: 'create_critico_registration'
  
    get '/registration/ristoratore', to: 'registration#new_ristoratore', as: 'new_ristoratore_registration'
    post '/registration/ristoratore', to: 'registration#create_ristoratore', as: 'create_ristoratore_registration'
  
    delete '/settings/:id', to: 'settings#destroy'
    resources :registration, only: [:new, :new_user, :new_critico, :new_ristoratore, :create_user, :create_critico, :create_ristoratore]
    
  
    resources :sessions, only: [:new, :create, :destroy]

    # Rotte per le competizioni
    resources :competizione, only: [:index, :create] do
      member do
        get 'assegna_punti', to: 'competizione#assegna_punti'
        post 'join', to: 'competizione#join_competition'
        delete 'delete_competizione', to: 'competizione#destroy'
        delete 'elimina_partecipante', to: 'competizione#elimina_partecipante'
      end
    end
    post '/competizione/create', to: 'competizione#create', as: 'create_competizione'
  
    #resources :prenotazioni, controller: 'prenotazione', only: [:create]
    resources :prenotazione do
        patch 'set_valida', on: :member  # Rotta per impostare la prenotazione come valida
    end
  
    #routes for profiles
    get 'critic_profile', to: 'critic_profile#show'
    get 'rest_profile', to: 'restaurateur_profiles#show'
    get 'admin_profile', to: 'admin_profile#show'
    delete 'admin_profile_user_delete', to: 'admin_profile#destroy'
    get 'user_profile', to: 'user_profile#show'
  
    #rotta per il menu
    #get 'menu', to: 'menus#show'
    # piatti
    #resources :piattos, only: [:index, :show, :create, :destroy, :new]
  
    # Rotta per la pagina di registrazione
    get 'signup', to: 'registration#new'

    post 'add_rest_to_favorites', to: 'favorites#add_rest_to_favorites'
    post 'add_event_to_favorites', to: 'favorites#add_event_to_favorites'
    post 'add_recipe_to_favorites', to: 'favorites#add_recipe_to_favorites'



    
    #route for placement
    get 'competizioni', to: 'competizione#index'
    get 'competizione_create', to: 'competizione#create'
    
    # Rotte per le pagine della dashboard
    get 'dashboard', to: 'restaurateur_profiles#show'
    get 'info', to: 'info#show'
    get 'settings', to: 'settings#show'
  
    # rotte per le pagine vetrina
    get 'public_restaurant_profile/:id', to: 'restaurateur_profiles#public_show', as: 'public_restaurant_profile'
    get 'public_user_profile/:id', to: 'user_profile#public_show', as: 'public_user_profile'
    get 'public_critic_profile/:id', to: 'critic_profile#public_show', as: 'public_critic_profile'
    get 'public_show_menus/:id', to: 'menus#public_show', as: 'public_show_menus'
  
    # per i tag
    post 'restaurateur_profiles/:tag_id/add_tag', to: 'restaurateur_profiles#add_tag', as: 'add_tag'
    post 'restaurateur_profiles/:tag_id/remove_tag', to: 'restaurateur_profiles#remove_tag', as: 'remove_tag'
    
    # rotte per il login
    # Rotta per il form di login (GET e POST)
    get 'login', to: 'sessions#new', as: :user_login
    post 'login', to: 'sessions#create_user'
    
    # Rotta per il form di login del ristoratore (GET e POST)
    get 'login_restaurateur', to: 'sessions#new', as: :restaurateur_login
    post 'login_restaurateur', to: 'sessions#create_restaurateur'
    
    # Rotta per il logout (DELETE)
    delete 'logout', to: 'sessions#destroy', as: :logout
    #get 'sessions/new'
      
    get 'home/index'
    
  
    # rotte per la pagina di ricerca
    get 'ricerca', to: 'ricerca#index'
    get 'logout', to: 'sessions#destroy'
    get 'ricerca/:id/map_info', to: 'ricerca#map_info'

  
    get 'support', to: 'support#index'
    
    resources :promotions, only: [:index]
    resources :competizioni, only: [:index]
    resource :restaurateur_profiles, only: [:show, :edit, :update] do
      post 'create_event', to: 'restaurateur_profiles#create_event'
      delete 'destroy_event/:id', to: 'restaurateur_profiles#destroy_event', as: 'destroy_event'
      post 'create_recipe', to: 'restaurateur_profiles#create_recipe'
      delete 'destroy_recipe/:id', to: 'restaurateur_profiles#destroy_recipe', as: 'destroy_recipe'
      post 'add_tag/:tag_id', to: 'restaurateur_profiles#add_tag'
      delete 'destroy_promotion/:id', to: 'restaurateur_profiles#destroy_promotion', as: 'destroy_promotion'
  
      post :create_promotion, on: :collection
  
      collection do
        patch 'update_info', to: 'restaurateur_profiles#update_info'
      end
    end
  
    resource :user_profile, only: [:show, :edit, :update] do
      put 'update', on: :member
    end

    resource :critic_profile, only: [:show, :edit, :update] do
      put 'update', on: :member
    end

    resource :menus
    resources :piattos, only: [:new, :create, :destroy]
  
    resource :settings, only: [:show, :edit, :update, :destroy]
    put 'update_credentials', to: 'settings#update_credentials'
    post 'verify_password', to: 'settings#verify_password'
    resources :eventi, only: [:create]
    resources :info, only: [:show] 
  
    resource :segnalaziones, only: [:create]
    get 'segnalazione_index', to: 'segnalaziones#index'
    delete 'segnalzaione_delete', to: 'segnalaziones#destroy'

    
    # Rotte aggiunte per creare e distruggere un dipendente
    post 'info/create_dipendente', to: 'info#create_dipendente', as: 'create_dipendente'
    delete 'info/destroy_dipendente/:id', to: 'info#destroy_dipendente', as: 'destroy_dipendente'

    #rotte per le risposte dei ristoratori
    post 'answer_create', to: 'answer#create'
    post 'answer_update', to: 'answer#update'
    delete 'answer_delete', to: 'answer#destroy'
  
    post 'update_review', to: 'reviews#update'
    #rotta per le recensioni
    resources :reviews, only: [:create, :destroy] do
      member do
        post 'add_like'
      end
    end

    # AUTHENTICATION ROUTES 
    get 'auth/:provider/callback', to: 'sessions#create' 
    get '/sign_out', to: 'sessions#destroy', as: :sign_out 
    get '/auth/google_oauth2', as: :sign_in
    get '/auth/failure' => 'sessions#failure'
  end

foodadvisor/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @recent_restaurants = Ristoratore.includes(cliente: :utente).where("ristoratores.created_at >= ?", 30.days.ago).order(created_at: :desc).limit(10)
    @upcoming_events = Evento.where("data >= ?", Date.today).order(data: :asc).limit(10)
    @reviews = Recensione.top_rated
  end
end

foodadvisor/app/helpers/home_helper.rb
module HomeHelper
end

foodadvisor/app/views/home/index.html.erb
<%= stylesheet_link_tag 'home', media: 'all' %>
<div class="homepage-container">
    <% if flash[:notice] %>
        <div class="alert alert-success" role="alert">
        <%= flash[:notice] %>
        </div>
    <% end %>

    <% if flash[:alert] %>
        <div class="alert alert-danger" role="alert">
        <%= flash[:alert] %>
        </div>
    <% end %>
    <% if logged_in? %>
        <div class="alert" style="font-style: italic; color: #00b072;">
        <p>Benvenuto,
            <% if session[:role] == 'User' %>
            <span style="font-weight: bold;"><%= @current_user.cliente.user.nome %></span>
            <% elsif session[:role] == 'Ristoratore' %>
            <span style="font-weight: bold;"><%= @current_user.cliente.ristoratore.nomeristorante %></span>
            <% elsif session[:role] == 'Critico' %>
            <span style="font-weight: bold;"><%= @current_user.cliente.user.nome %></span>
            <% elsif session[:role] == 'Admin' %>
            <span style="font-weight: bold;"><%= @current_user.admin.nome %></span>
            <% end %>
            !
        </p> 
        </div>
    <% end %>
    <div class="h1-container">
        <h1>Consigliati per te</h1>
    </div>
    <div class="recents-container">
        <div class="restaurants-text" style="display: flex; flex-direction: column; justify-content: center; align-items: center;">
          <h2>Nuovi Ristoratori</h2>
          <p>Ristoratori aggiunti di recente su FoodAdvisor. Recensiscili per primo!</p>
        </div>
        
        <div class="restaurants-grid" style="animation: scrollLeft 1s;">
            <% @recent_restaurants.each do |ristoratore| %>
            <% @media = ristoratore.media_stelle%>
            <% @numero = ristoratore.n_recensioni%>


                <%= link_to public_restaurant_profile_path(ristoratore.id), class: 'restaurant-link' do %>
                <div class="restaurant-box">
                    <% if ristoratore.cliente.foto.present? %>
                        <%= image_tag ristoratore.cliente.foto %>
                    <% else %>
                        <%= image_tag "background.jpg" %>
                    <% end %>
                    <div class="text-overlay">
                        <%= ristoratore.nomeristorante %> 
                        <p style="font-weight: normal;"><%= @media %><span style="font-weight: normal;"><ion-icon name="star" style="font-size: 15px; color: #00b072; margin-left: 10px;"></ion-icon></p>
                        <p style="font-weight: normal; font-style: italic;"><%= @numero %> recensioni</p>
                    </div>
                </div>
                <% end %>
            <% end %>          
        </div>
      </div>

    <div class="earn-points-container">
        <%= image_tag 'trophy.png' %>
        <div class="text-container">
        <h3 style="color: black;">Guadagna punti!</h3>
        <p style="color: black;">Recensisci i ristoranti e partecipa ai tornei di FoodAdvisor per guadagnare punti!</p>
        <a href="<%= competizioni_path %>"><button type="button">Cominciamo!</button></a>
        </div>
    </div>

    <div class="recents-container">
        <div class="events-text" style="display: flex; flex-direction: column; justify-content: center; align-items: center;">
            <h2>Eventi da scoprire</h2>
        <p>Scopri gli eventi più recenti e popolari!</p>

        </div>
        
        <div class="restaurants-grid">
            <% @upcoming_events.each do |evento| %>
                <%= link_to public_restaurant_profile_path(evento.ristoratore_id), class: 'restaurant-link' do %>
              <div class="restaurant-box">
                <% if evento.locandina.present? %>
                    <%= image_tag evento.locandina, class: 'evento-foto'  %>
                <% else %>
                    <%= image_tag 'background.jpg', class: 'evento-foto' %>
                <% end %> 
                <div class="text-overlay" style="background-color: white; text-shadow: none; color: black; bottom: 0; left: 0; width: 100%; border-radius: 0; border: 1px solid #c9c9c9;">
                  <p><%= evento.nome %></p>
                  <p style="font-size: 13px; font-weight: normal;"><%= evento.descrizione %></p>
                  <p style="font-size: 13px; font-weight: normal;"><%= evento.data %></p>
                  <p style="font-size: 13px; font-weight: normal;"><%= evento.luogo %></p>
                </div>
              </div>
              <% end %>
            <% end %>
          </div>
          

        
        
    </div>
    <div class="most-rewarded-container" style="margin-top: 30px; display: flex; align-items: center; width: 100%; background-color:antiquewhite;">
        <div class="most-rewarded-text" style="margin-left: 20%; width: 20%; margin-top: 30px;">
            <h1 style="color: black;">Scopri i Ristoranti più premiati</h1>
            <p style="color: black;">Fatti guidare dagli altri utenti e dai critici per scoprire ristoranti particolarmente graditi.</p>
            <a href="<%= classifiche_path %>"><button type="button">Vediamoli!</button></a>

        </div>
        <div class="most-rewarded-image" style="margin-left: 10%;">
            <%= image_tag 'rank1.png' %>



        </div>
    </div>  

    <div class="popular-reviews-and-reserv-container" style="display: flex; margin-top: 30px; justify-content: space-evenly; margin-bottom: 30px;">
        <div class="reviews-container" style="padding: 10px; border-radius: 10px;">
            <h3 style="margin-bottom: 20px;">Recensioni Popolari</h3>
            <div class="popular-reviews-container" style="display: flex; flex-direction: column; height: 300px; overflow-y: scroll; ">
                <% if @reviews.any? %>
                    <% @reviews.each do |review| %>
                        <%= link_to public_user_profile_path(review.cliente.user.id), class: 'linksito' do %>
                        <div class="popular-reviews-box" style="display: flex; width: 600px; ">
                            <%= image_tag 'background.jpg' %>
                            <div class="popular-reviews-box-text">
                                <h3><%= review.cliente.user.username %></h3>
                                <p style="font-style: italic; font-size: 13px;"><%= review.ristoratore.nomeristorante %><span> - </span><span style="font-style: normal;"><%= review.created_at.strftime('%d/%m/%Y') %></span></p>
                                <% review.stelle.times do %>
                                    <ion-icon name="star" style="font-size: 15px;"></ion-icon>
                                <% end %>
                                <p><%= review.commento %></p>
                                <p style="font-weight: bold;">Likes: <span style="font-weight: normal;"><%= review.like %></p>
                            </div>
                        </div>
                        <hr class="solid" id="divider">
                        <% end %>
                    <% end %>
                <% else %>
                    <p>Non sono state lasciate recensioni</p>
                <% end %>
            </div>
        </div>
        <div class="reserv-container" style="margin-left: 30px; display: flex; justify-content: center; align-items: center; width: 20%;">
            <% if session[:user_id].nil? %>
                <h2>Accedi al <a href="<%= login_path %>"><span style="font-style: italic; cursor: pointer; color: #00b072;">tuo account</span></a> per effettuare e visualizzare le tue prenotazioni!</h2>
            <% elsif session[:role] == 'Admin' %>
                <h2>Accedi al <a href="<%= admin_profile_path %>"><span style="font-style: italic; cursor: pointer; color: #00b072;">tuo account</span></a> per effettuare e visualizzare le tue prenotazioni!</h2>
            <% elsif session[:role] == 'Ristoratore' %>
                <h2>Accedi al <a href="<%= restaurateur_profiles_path %>"><span style="font-style: italic; cursor: pointer; color: #00b072;">tuo account</span></a> per effettuare e visualizzare le tue prenotazioni!</h2>
            <% elsif session[:role] == 'Critico' %>
                <h2>Accedi al <a href="<%= critic_profile_path %>"><span style="font-style: italic; cursor: pointer; color: #00b072;">tuo account</span></a> per effettuare e visualizzare le tue prenotazioni!</h2>
            <% elsif session[:role] == 'User' %>
                <h2>Accedi al <a href="<%= user_profile_path %>"><span style="font-style: italic; cursor: pointer; color: #00b072;">tuo account</span></a> per effettuare e visualizzare le tue prenotazioni!</h2>
            <% else %>
                <h2>Accedi al <a href="<%= root_path %>"><span style="font-style: italic; cursor: pointer; color: #00b072;">tuo account</span></a> per effettuare e visualizzare le tue prenotazioni!</h2>
            <% end %>
        </div>
    </div>
</div>