foodadvisor/config/routes.rb
Rails.application.routes.draw do
    
    get 'user_notifications/index'
    get 'preferiti/show'
    get 'user_profile/edit'
    get 'user_profile/show'
    put 'user_profile/update'
    get 'admin_profile/edit'
    get 'admin_profile/show'
    get 'profile/show'
    get 'critic_profile/show'
    get 'critic_profile/edit'
    put 'critic_profile/update'
    get 'competizione/index'
    get 'support/index'
    
    # rotta per la pagina principale
    root 'home#index'
    get 'root', to: 'home#index' 

    #caalback fb
    post 'auth/facebook/callback', to: 'sessions#facebook'
  
    # Defines the root path route ("/")
    # root "posts#index"

    # config/routes.rb
  resources :favorites, only: [] do
    delete :remove_rest_from_favorites, on: :collection
  end

  # config/routes.rb
  resources :favorites, only: [] do
    delete :remove_recipe_from_favorites, on: :collection
  end


  
    get 'classifiche', to: 'classifiche#index'
    get 'supporto', to: 'supporto#index'

    get 'about', to: 'about#index'

    
    resources :problems do
      member do
        put 'aggiorna_stato_problema', to: 'problems#aggiorna_stato_problema'
      end
    end

    resources :notifications, only: [:new, :create]
    resources :user_notifications, only: [:index]

    post 'restaurateur_profiles/update_pin', to: 'restaurateur_profiles#update_pin', as: 'update_pin_restaurateur_profile'
    
    # grafico
    get 'bookings_per_week', to: 'info#bookings_per_week'
    get 'daily_bookings_and_events', to: 'info#daily_bookings_and_events'

    # grafici personali
    get 'daily_bookings', to: 'critic_profile#daily_bookings'
    get 'monthly_bookings', to: 'critic_profile#monthly_bookings'
    get 'daily_bookings_user', to: 'user_profile#daily_bookings_user'
    get 'monthly_bookings_user', to: 'user_profile#monthly_bookings_user'
  
    #
    # Rotta per il form di login (GET e POST)
    get 'login', to: 'sessions#new'
  
    get '/registration/user', to: 'registration#new_user', as: 'new_user_registration'
    post '/registration/user', to: 'registration#create_user', as: 'create_user_registration'
  
    get '/registration/critico', to: 'registration#new_critico', as: 'new_critico_registration'
    post '/registration/critico', to: 'registration#create_critico', as: 'create_critico_registration'
  
    get '/registration/ristoratore', to: 'registration#new_ristoratore', as: 'new_ristoratore_registration'
    post '/registration/ristoratore', to: 'registration#create_ristoratore', as: 'create_ristoratore_registration'
  
    delete '/settings/:id', to: 'settings#destroy'
    resources :registration, only: [:new, :new_user, :new_critico, :new_ristoratore, :create_user, :create_critico, :create_ristoratore]
    
  
    resources :sessions, only: [:new, :create, :destroy]

    # Rotte per le competizioni
    resources :competizione, only: [:index, :create] do
      member do
        get 'assegna_punti', to: 'competizione#assegna_punti'
        post 'join', to: 'competizione#join_competition'
        delete 'delete_competizione', to: 'competizione#destroy'
        delete 'elimina_partecipante', to: 'competizione#elimina_partecipante'
      end
    end
    post '/competizione/create', to: 'competizione#create', as: 'create_competizione'
  
    #resources :prenotazioni, controller: 'prenotazione', only: [:create]
    resources :prenotazione do
        patch 'set_valida', on: :member  # Rotta per impostare la prenotazione come valida
    end
  
    #routes for profiles
    get 'critic_profile', to: 'critic_profile#show'
    get 'rest_profile', to: 'restaurateur_profiles#show'
    get 'admin_profile', to: 'admin_profile#show'
    delete 'admin_profile_user_delete', to: 'admin_profile#destroy'
    get 'user_profile', to: 'user_profile#show'
  
    #rotta per il menu
    #get 'menu', to: 'menus#show'
    # piatti
    #resources :piattos, only: [:index, :show, :create, :destroy, :new]
  
    # Rotta per la pagina di registrazione
    get 'signup', to: 'registration#new'

    post 'add_rest_to_favorites', to: 'favorites#add_rest_to_favorites'
    post 'add_event_to_favorites', to: 'favorites#add_event_to_favorites'
    post 'add_recipe_to_favorites', to: 'favorites#add_recipe_to_favorites'



    
    #route for placement
    get 'competizioni', to: 'competizione#index'
    get 'competizione_create', to: 'competizione#create'
    
    # Rotte per le pagine della dashboard
    get 'dashboard', to: 'restaurateur_profiles#show'
    get 'info', to: 'info#show'
    get 'settings', to: 'settings#show'
  
    # rotte per le pagine vetrina
    get 'public_restaurant_profile/:id', to: 'restaurateur_profiles#public_show', as: 'public_restaurant_profile'
    get 'public_user_profile/:id', to: 'user_profile#public_show', as: 'public_user_profile'
    get 'public_critic_profile/:id', to: 'critic_profile#public_show', as: 'public_critic_profile'
    get 'public_show_menus/:id', to: 'menus#public_show', as: 'public_show_menus'
  
    # per i tag
    post 'restaurateur_profiles/:tag_id/add_tag', to: 'restaurateur_profiles#add_tag', as: 'add_tag'
    post 'restaurateur_profiles/:tag_id/remove_tag', to: 'restaurateur_profiles#remove_tag', as: 'remove_tag'
    
    # rotte per il login
    # Rotta per il form di login (GET e POST)
    get 'login', to: 'sessions#new', as: :user_login
    post 'login', to: 'sessions#create_user'
    
    # Rotta per il form di login del ristoratore (GET e POST)
    get 'login_restaurateur', to: 'sessions#new', as: :restaurateur_login
    post 'login_restaurateur', to: 'sessions#create_restaurateur'
    
    # Rotta per il logout (DELETE)
    delete 'logout', to: 'sessions#destroy', as: :logout
    #get 'sessions/new'
      
    get 'home/index'
    
  
    # rotte per la pagina di ricerca
    get 'ricerca', to: 'ricerca#index'
    get 'logout', to: 'sessions#destroy'
    get 'ricerca/:id/map_info', to: 'ricerca#map_info'

  
    get 'support', to: 'support#index'
    
    resources :promotions, only: [:index]
    resources :competizioni, only: [:index]
    resource :restaurateur_profiles, only: [:show, :edit, :update] do
      post 'create_event', to: 'restaurateur_profiles#create_event'
      delete 'destroy_event/:id', to: 'restaurateur_profiles#destroy_event', as: 'destroy_event'
      post 'create_recipe', to: 'restaurateur_profiles#create_recipe'
      delete 'destroy_recipe/:id', to: 'restaurateur_profiles#destroy_recipe', as: 'destroy_recipe'
      post 'add_tag/:tag_id', to: 'restaurateur_profiles#add_tag'
      delete 'destroy_promotion/:id', to: 'restaurateur_profiles#destroy_promotion', as: 'destroy_promotion'
  
      post :create_promotion, on: :collection
  
      collection do
        patch 'update_info', to: 'restaurateur_profiles#update_info'
      end
    end
  
    resource :user_profile, only: [:show, :edit, :update] do
      put 'update', on: :member
    end

    resource :critic_profile, only: [:show, :edit, :update] do
      put 'update', on: :member
    end

    resource :menus
    resources :piattos, only: [:new, :create, :destroy]
  
    resource :settings, only: [:show, :edit, :update, :destroy]
    put 'update_credentials', to: 'settings#update_credentials'
    post 'verify_password', to: 'settings#verify_password'
    resources :eventi, only: [:create]
    resources :info, only: [:show] 
  
    resource :segnalaziones, only: [:create]
    get 'segnalazione_index', to: 'segnalaziones#index'
    delete 'segnalzaione_delete', to: 'segnalaziones#destroy'

    
    # Rotte aggiunte per creare e distruggere un dipendente
    post 'info/create_dipendente', to: 'info#create_dipendente', as: 'create_dipendente'
    delete 'info/destroy_dipendente/:id', to: 'info#destroy_dipendente', as: 'destroy_dipendente'

    #rotte per le risposte dei ristoratori
    post 'answer_create', to: 'answer#create'
    post 'answer_update', to: 'answer#update'
    delete 'answer_delete', to: 'answer#destroy'
  
    post 'update_review', to: 'reviews#update'
    #rotta per le recensioni
    resources :reviews, only: [:create, :destroy] do
      member do
        post 'add_like'
      end
    end

    # AUTHENTICATION ROUTES 
    get 'auth/:provider/callback', to: 'sessions#create' 
    get '/sign_out', to: 'sessions#destroy', as: :sign_out 
    get '/auth/google_oauth2', as: :sign_in
    get '/auth/failure' => 'sessions#failure'
  end

foodadvisor/app/controllers/user_profile_controller.rb
class UserProfileController < ApplicationController
  layout :determine_layout

  before_action :require_logged_in, except: [:public_show]
  before_action :require_customer, except: [:public_show]
  before_action :set_user, only: [:show, :edit, :update, :monthly_bookings_user, :daily_bookings_user]

  def show
    @recensioni = Recensione.where(cliente_id: current_user.cliente.id).order(created_at: :desc)
    @iscrizioni = UserCompetition.where(user_id: current_user.cliente.user.id)
    @prenotazioni = Prenotazione.where(user_id: current_user.cliente.user.id).where('data >= ?', Date.today).order(valide: :desc).order(data: :asc)
    @premi = Premi.where(id: current_user.cliente.user.id)
    @user = Utente.find(@current_user.id)
  end

  def edit
  end

  def public_show
    @user = User.find(params[:id])
    @iscrizioni = UserCompetition.where(user_id: @user.id)
    @reviews = Recensione.where(cliente_id: @user.cliente.id).order(created_at: :desc).order(pinnata: :desc)

    @posizioni = {}
    @iscrizioni.each do |iscrizione|
      competizione = Competizione.find(iscrizione.competizione_id)
      @posizioni[competizione.id] = competizione.posizione_utente(@user.id)
    end
  end

  def daily_bookings_user
    year = params[:year].to_i
    month = params[:month].to_i
    day = params[:day].to_i

    # Formatta la data come stringa 'YYYY-MM-DD'
    formatted_date = Date.new(year, month, day).strftime('%Y-%m-%d')

    # Query per le prenotazioni
    @prenotazioni_oggi = Prenotazione.where(data: formatted_date, valida: true, user_id: @user.cliente.user.id)

    # Renderizza il JSON con tutte le informazioni
    render json: {
      prenotazioni: @prenotazioni_oggi
    }
  end

  def monthly_bookings_user
    year = params[:year].to_i
    month = params[:month].to_i

    start_date = Date.new(year, month, 1)
    end_date = start_date.end_of_month

    # Formatta le date come stringhe 'YYYY-MM-DD'
    start_date_str = start_date.strftime('%Y-%m-%d')
    end_date_str = end_date.strftime('%Y-%m-%d')

    # Query per le prenotazioni del mese
    prenotazioni = Prenotazione.where('data >= ? AND data <= ? AND valida = ? AND user_id = ?', start_date_str, end_date_str, true, @user.cliente.user.id)

    render json: {
      bookings: prenotazioni
    }
  end

  private

  def determine_layout
    action_name == 'public_show' ? 'application' : 'with_sidebar'
  end

  def set_user
    @user = @current_user
  end

  def utente_params
    params.require(:utente).permit(:email, :telefono, cliente_attributes: [:id, :foto, user_attributes: [:id, :username, :nome, :cognome, :datanascita]])
  end

  def require_logged_in
    unless logged_in?
      redirect_to login_path
    end
  end

  def require_customer
    unless session[:role] == 'User'
      redirect_to root_path
    end
  end

  def save_locandina(image)
    # Genera un nome univoco per l'immagine
    filename = "#{SecureRandom.hex(8)}_#{image.original_filename}"
    # Percorso completo di salvataggio
    directory = Rails.root.join('app', 'assets', 'images')
    FileUtils.mkdir_p(directory) unless File.directory?(directory) # Crea la directory se non esiste
    path = File.join(directory, filename)
    # Salva il file nell'immagine
    File.open(path, 'wb') do |file|
      file.write(image.read)
    end
    
    filename
  end

end

foodadvisor/app/views/user_profile/edit.html.erb
<%= link_to 'Salva', user_profile_path %>

foodadvisor/app/views/user_profile/public_show.html.erb
<div class="pagina-vetrina-utente">
<% if flash[:notice] %>
      <div class="alert alert-success" role="alert">
        <%= flash[:notice] %>
      </div>
    <% end %>

    <% if flash[:alert] %>
      <div class="alert alert-danger" role="alert">
        <%= flash[:alert] %>
      </div>
    <% end %>
    <h1 style="font-size: 40px; margin-bottom: 20px;">Profilo di <span style="color: #28a745;"><%= @user.username %></span></h1>
    <div class="public-u-foto-info">
        <div class="public-u-foto">
            <% if @user.cliente.foto.present? %>
                <%= image_tag @user.cliente.foto %>
            <% else %>
                <%= image_tag 'user.jpg' %>
            <% end %>
        </div>
        <div class="public-u-info">
            <p style="font-weight: bold;">Nome: <span style="font-weight: normal;"><%= @user.nome %></span></p>
            <p style="font-weight: bold;">Cognome: <span style="font-weight: normal;"><%= @user.cognome %></span></p>
            <p style="font-weight: bold;">Iscrizione: <span style="font-weight: normal;"><%= @user.created_at.strftime('%d/%m/%Y') %></span></p>
        </div>
    </div>
    <% if session[:role]!='Admin' && @current_user.present? && @current_user.cliente.id != @user.cliente.id%> 
      <div class="public-u-follow-btn">
        <button type="button" class="report-icon" id="report-rest" style="background-color: rgb(221, 60, 60);" data-report="<%= @user.id %>" data-type="user">Segnala</button>
      </div>
    <% end %>

    <hr class="solid" id="divider" style="width: 80%;">
    <h1>Ultime Recensioni</h1>

    <div class="r-pub-recensioni" style="max-height: 400px; overflow-y: scroll;">
        <% if @reviews.any? %>
            <% @reviews.each do |review| %>
                <div class="public-r-reviews" style="margin-bottom: 20px; display: flex; flex-direction: row; justify-content: space-between; ">
                    <div class="public-foto-details">
                        <% if review.ristoratore.cliente.foto.present? %>
                            <%= image_tag review.ristoratore.cliente.foto %> <!-- Supponendo che il ristorante abbia un'immagine associata -->
                        <% else %>
                            <%= image_tag 'background.jpg' %>
                        <% end %>
                        <div class="public-review-details">
                            <p>
                                <%= link_to public_restaurant_profile_path(review.ristoratore.id), style: "color: black; " do %>
                                  <%= review.ristoratore.nomeristorante %><br>
                                <% end %>
                                
                                <% review.stelle.times do %>
                                    <ion-icon name="star" style="font-size: 15px;"></ion-icon>
                                <% end %> <br>
                                <%= truncate(review.commento, length: 200) %><br> <!-- Tronca il testo della recensione a 200 caratteri -->
                                <span style="font-style: italic; font-size: 13px;">in data <%= review.created_at.strftime('%d/%m/%Y') %></span>
                            </p>
                        </div>
                    </div>
                    <div class="public-r-rev-icon">
                    <% if session[:role] == 'Admin' %>
                      <i class="fa-solid fa-trash"></i>
                    <% elsif @current_user.present? %>
                        <% if @current_user.cliente.id != review.cliente_id%>
                        <i class="fa fa-exclamation-circle report-icon" data-report="<%= review.id %>" data-type="recensione"></i>
                        <% end %>
                  <% end %> 
                    </div>
                </div>
            <% end %>
        <% else %>
            <p Style="color: gray; ">L'utente non ha lasciato alcuna recensione.</p>
        <% end %>
    </div>


    <hr class="solid" id="divider" style="width: 80%;">
    <h1>Competizioni a cui l'utente partecipa</h1>

    <div class="public-u-competitions">
        <% if @iscrizioni.any? %>
            <% @iscrizioni.each do |iscrizione| %>
            <% competizione = Competizione.find(iscrizione.competizione_id) %>
        <div class="public-u-competition-box">
        <% if competizione.locandina.present? %>
            <%= image_tag competizione.locandina %>
            <% else  %>
            <%= image_tag "background.jpg"  %>
            <% end  %>
            <div class="public-u-competition-box-info">
                <p style="font-weight: bold;">Nome Competizione: <span style="font-weight: normal;"> <%= competizione.nome %></span></p>
                <p style="font-weight: bold;">Punti: <span style="font-weight: normal;"><%= iscrizione.punti_competizione %></span></p>
                <p style="font-weight: bold;">Posizione in Classifica: <span style="font-weight: normal;"><%= @posizioni[competizione.id] %></span></p>
            </div>

        </div>
        <% end %>
          <% else %>
            <p Style="color: gray; ">Nessuna competizione trovata</p>
          <% end %>
    </div>

</div>

<div id="reportModal" class="modal">
<div class="modal-content">
  <span id="closeReport" class="close">&times;</span>
  <h2>Fai la tua segnalazione</h2>
  <% if current_user.present? %>
    <%= form_with( url: segnalaziones_path, method: "post", local: true) do |form| %>
      <%= form.hidden_field :data_id%>
      <%= form.hidden_field :type%>
      Motivo della segnalazione
      <br><br>
      <%= form.label :commento, "Commento:" %>
      <%= form.text_area :commento, id: "commento", rows: 4, cols: 50 %>
      <br><br>
      <%= form.submit "Invia" %>
    <% end %>
  <% end %>
</div>
</div>


<script>
//JS modale segnalazione
document.addEventListener("DOMContentLoaded", function() {
  
  document.querySelectorAll('.report-icon').forEach(icon => {
    icon.addEventListener('click', (event) => {
      const review = event.target.getAttribute('data-report');
      const type = event.target.getAttribute('data-type');

      document.getElementById('data_id').value = review;
      document.getElementById('type').value = type;


      openModal();
    });
  });

  function openModal() {
    document.getElementById('reportModal').style.display = 'block';
  }

  function closeReportModal() {
    document.getElementById('reportModal').style.display = 'none';
  }

  window.onclick = function(event) {
    var modal = document.getElementById('reportModal');
    if (event.target == modal) {
      modal.style.display = 'none';
    }
  }
  document.querySelector('#closeReport').onclick = closeReportModal;
});
</script>

foodadvisor/app/views/user_profile/show.html.erb
<%= javascript_include_tag 'user_profile', 'data-turbolinks-track': 'reload' %>

<div class="p-user-profile">
  <% if flash[:notice] %>
    <div class="alert alert-success" role="alert">
      <%= flash[:notice] %>
    </div>
  <% end %>

  <% if flash[:alert] %>
    <div class="alert alert-danger" role="alert">
      <%= flash[:alert] %>
    </div>
  <% end %>

  <div class="p-user-photo-details">
    <% if @current_user.cliente.foto.present? %>
      <%= image_tag @current_user.cliente.foto %>
    <% else %>
      <%= image_tag 'user.jpg' %> <!-- Immagine competizione -->
    <% end %>
    <div class="p-user-details">
      <p style="font-weight: bold;">Username: <span id="right-side-requisiti" style="font-weight: normal;"><%= @current_user.cliente.user.username %></span></p>
      <p style="font-weight: bold;">Nome: <span id="right-side-requisiti" style="font-weight: normal;"><%= @current_user.cliente.user.nome %></span></p>
      <p style="font-weight: bold;">Cognome: <span id="right-side-requisiti" style="font-weight: normal;"><%= @current_user.cliente.user.cognome %></span></p>
      <p style="font-weight: bold;">Data di Nascita: <span id="right-side-requisiti" style="font-weight: normal;"><%= @current_user.cliente.user.datanascita %></span></p>
      <p style="font-weight: bold;">Data Iscrizione: <span id="right-side-requisiti" style="font-weight: normal;"><%= @current_user.cliente.user.created_at.strftime('%d/%m/%Y') %></span></p>
      <p style="font-weight: bold;">Email: <span id="right-side-requisiti" style="font-weight: normal;"><%= @current_user.cliente.utente.email %></span></p>
      <p style="font-weight: bold;">Telefono: <span id="right-side-requisiti" style="font-weight: normal;"><%= @current_user.cliente.utente.telefono %></span></p>
    </div>
    <% if @user.tmp_password.present? %>
      <p class="tmp_password">La tua password temporanea è: <%= @user.tmp_password %> cambiala al più presto!</p>
    <% end %>
  </div>

  <hr id="divider" class="solid">
  <h1>I tuoi premi</h1>
  <div class="premicompetizioni">
    <% if @premi.any? %>
      <% @premi.each do |premio| %>
        <div class="premio-box">
          <h3>Competizione: <%= premio.nomecompetizione %></h3>
          <p>Nome del Premio: <%= premio.nome %></p>
          <p>Data di Inizio: <%= premio.data_inizio.strftime('%d/%m/%Y') %></p>
          <p>Data di Fine: <%= premio.data_fine.strftime('%d/%m/%Y') %></p>
        </div>
      <% end %>
    <% else %>
      <p style="color:gray;">Partecipa alle competizioni per ottenere dei premi.</p>
    <% end %>
  </div>

  <hr id="divider" class="solid">
  <h1>I tuoi impegni</h1>
  <div class="impegniPersonali">
    <div class="impegniSinistra">
      <div id="calendario">
      </div>
    </div>
    <div class="impegniDestra">
      <div id="impegniGiornalieri">
      </div>
    </div>
  </div>
  <hr id="divider" class="solid">

  <h1>Ultime recensioni</h1>
  <div class="r-pub-recensioni" style="max-height: 400px; overflow-y: scroll; box-shadow: 0 0 10px rgba(0, 0, 0, 0.1); padding: 1%; ">
        <% if @recensioni.any? %>
            <% @recensioni.each do |review| %>
                <div class="public-r-reviews" style="margin-bottom: 20px; display: flex; flex-direction: row; justify-content: space-between; ">
                    <div class="public-foto-details">
                        <% if review.ristoratore.cliente.foto.present? %>
                            <%= image_tag review.ristoratore.cliente.foto %> <!-- Supponendo che il ristorante abbia un'immagine associata -->
                        <% else %>
                            <%= image_tag 'background.jpg' %>
                        <% end %>
                        <div class="public-review-details">
                            <p>
                                <%= link_to public_restaurant_profile_path(review.ristoratore.id), style: "color: black; " do %>
                                  <%= review.ristoratore.nomeristorante %><br>
                                <% end %>
                                
                                <% review.stelle.times do %>
                                    <ion-icon name="star" style="font-size: 15px;"></ion-icon>
                                <% end %> <br>
                                <%= truncate(review.commento, length: 200) %><br> <!-- Tronca il testo della recensione a 200 caratteri -->
                                <span style="font-style: italic; font-size: 13px;">in data <%= review.created_at.strftime('%d/%m/%Y') %></span>
                            </p>
                        </div>
                    </div>
                </div>
            <% end %>
        <% else %>
            <p Style="color: gray; ">L'utente non ha lasciato alcuna recensione.</p>
        <% end %>
    </div>


  <hr id="divider" class="solid">
  <h1>Competizioni a cui sei iscritto</h1>
  <div class="p-user-fav-events">
    <% if @iscrizioni.any? %>
      <% @iscrizioni.each do |iscrizione| %>
        <% competizione = Competizione.find(iscrizione.competizione_id) %>
        <div class="comp-box" data-id="<%= competizione.id %>" data-nome="<%= competizione.nome %>" data-descrizione="<%= competizione.descrizione %>" data-requisiti="<%= competizione.requisiti %>" data-premio="<%= competizione.premio %>" data-locandina="<%= competizione.locandina %>">
          <% if competizione.locandina.present? %>
            <%= image_tag competizione.locandina %>
          <% else %>
            <%= image_tag 'background.jpg' %>
          <% end %>
          <div class="text-overlay" style="background-color: white; text-shadow: none; color: black; bottom: 0; left: 0; width: 100%; border-radius: 0; border: 1px solid #c9c9c9;">
            <p><%= competizione.nome %></p>
            <p style="font-size: 13px; font-weight: normal;"><%= competizione.descrizione %></p>
            <p style="font-size: 13px; font-weight: normal;">Requisiti: <%= competizione.requisiti %> <span>Premi: <%= competizione.premio %></span></p>
            <%= button_to 'Disiscriviti', elimina_partecipante_competizione_path(competizione), method: :delete, data: { confirm: 'Sei sicuro di voler eliminare questa competizione?' }, class: 'btn btn-danger' %>
          </div>
        </div>
      <% end %>
    <% else %>
      <p style="color: gray;">Non sei ancora iscritto ad una competizione</p>
    <% end %>
  </div>

  <hr id="divider" class="solid">
  <h1>Le tue Prenotazioni</h1>
  <div class="p-user-reservs" style="max-height: 400px; overflow-x: scroll;">
    <% if @prenotazioni.any? %>
      <% @prenotazioni.each do |prenotazione| %>
        <% ristorante_prenotazione = Ristoratore.find(prenotazione.ristoratore_id) %>
        <div class="p-user-reserv-box">
          <p style="font-weight: bold;">Ristorante: <span id="right-side-requisiti" style="font-weight: normal;"><%= ristorante_prenotazione.nomeristorante %></span></p>
          <p style="font-weight: bold;">Numero Persone: <span id="right-side-requisiti" style="font-weight: normal;"><%= prenotazione.numero_persone %></span></p>
          <p style="font-weight: bold;">Data: <span id="right-side-requisiti" style="font-weight: normal;"><%= prenotazione.data %></span></p>
          <p style="font-weight: bold;">Orario: <span id="right-side-requisiti" style="font-weight: normal;"><%= prenotazione.orario.strftime('%H:%M') %></span></p>
          <p style="font-weight: bold;">Effettuata: <span id="right-side-requisiti" style="font-weight: normal;"><%= prenotazione.created_at.strftime('%d/%m/%Y') %></span></p>
          <br>
          <p style="font-weight: bold; text-align: center;">
            <% if prenotazione.valida? %>
              Accettata
            <% else %>
              In attesa
            <% end %>
          </p>
        </div>
      <% end %>
    <% else %>
      <p style="color: gray;">Nessuna prenotazione trovata</p>
    <% end %>
  </div>
</div>

<style>
  .tmp_password {
    background-color: #ffcccc;
    padding: 10px;
    border: 1px solid #e74c3c;
    border-radius: 5px;
    text-align: right;
  }

  .tmp_password strong {
    font-weight: bold;
  }

</style>