foodadvisor/config/routes.rb
Rails.application.routes.draw do
    
    get 'user_notifications/index'
    get 'preferiti/show'
    get 'user_profile/edit'
    get 'user_profile/show'
    put 'user_profile/update'
    get 'admin_profile/edit'
    get 'admin_profile/show'
    get 'profile/show'
    get 'critic_profile/show'
    get 'critic_profile/edit'
    put 'critic_profile/update'
    get 'competizione/index'
    get 'support/index'
    
    # rotta per la pagina principale
    root 'home#index'
    get 'root', to: 'home#index' 

    #caalback fb
    post 'auth/facebook/callback', to: 'sessions#facebook'
  
    # Defines the root path route ("/")
    # root "posts#index"

    # config/routes.rb
  resources :favorites, only: [] do
    delete :remove_rest_from_favorites, on: :collection
  end

  # config/routes.rb
  resources :favorites, only: [] do
    delete :remove_recipe_from_favorites, on: :collection
  end


  
    get 'classifiche', to: 'classifiche#index'
    get 'supporto', to: 'supporto#index'

    get 'about', to: 'about#index'

    
    resources :problems do
      member do
        put 'aggiorna_stato_problema', to: 'problems#aggiorna_stato_problema'
      end
    end

    resources :notifications, only: [:new, :create]
    resources :user_notifications, only: [:index]

    post 'restaurateur_profiles/update_pin', to: 'restaurateur_profiles#update_pin', as: 'update_pin_restaurateur_profile'
    
    # grafico
    get 'bookings_per_week', to: 'info#bookings_per_week'
    get 'daily_bookings_and_events', to: 'info#daily_bookings_and_events'

    # grafici personali
    get 'daily_bookings', to: 'critic_profile#daily_bookings'
    get 'monthly_bookings', to: 'critic_profile#monthly_bookings'
    get 'daily_bookings_user', to: 'user_profile#daily_bookings_user'
    get 'monthly_bookings_user', to: 'user_profile#monthly_bookings_user'
  
    #
    # Rotta per il form di login (GET e POST)
    get 'login', to: 'sessions#new'
  
    get '/registration/user', to: 'registration#new_user', as: 'new_user_registration'
    post '/registration/user', to: 'registration#create_user', as: 'create_user_registration'
  
    get '/registration/critico', to: 'registration#new_critico', as: 'new_critico_registration'
    post '/registration/critico', to: 'registration#create_critico', as: 'create_critico_registration'
  
    get '/registration/ristoratore', to: 'registration#new_ristoratore', as: 'new_ristoratore_registration'
    post '/registration/ristoratore', to: 'registration#create_ristoratore', as: 'create_ristoratore_registration'
  
    delete '/settings/:id', to: 'settings#destroy'
    resources :registration, only: [:new, :new_user, :new_critico, :new_ristoratore, :create_user, :create_critico, :create_ristoratore]
    
  
    resources :sessions, only: [:new, :create, :destroy]

    # Rotte per le competizioni
    resources :competizione, only: [:index, :create] do
      member do
        get 'assegna_punti', to: 'competizione#assegna_punti'
        post 'join', to: 'competizione#join_competition'
        delete 'delete_competizione', to: 'competizione#destroy'
        delete 'elimina_partecipante', to: 'competizione#elimina_partecipante'
      end
    end
    post '/competizione/create', to: 'competizione#create', as: 'create_competizione'
  
    #resources :prenotazioni, controller: 'prenotazione', only: [:create]
    resources :prenotazione do
        patch 'set_valida', on: :member  # Rotta per impostare la prenotazione come valida
    end
  
    #routes for profiles
    get 'critic_profile', to: 'critic_profile#show'
    get 'rest_profile', to: 'restaurateur_profiles#show'
    get 'admin_profile', to: 'admin_profile#show'
    delete 'admin_profile_user_delete', to: 'admin_profile#destroy'
    get 'user_profile', to: 'user_profile#show'
  
    #rotta per il menu
    #get 'menu', to: 'menus#show'
    # piatti
    #resources :piattos, only: [:index, :show, :create, :destroy, :new]
  
    # Rotta per la pagina di registrazione
    get 'signup', to: 'registration#new'

    post 'add_rest_to_favorites', to: 'favorites#add_rest_to_favorites'
    post 'add_event_to_favorites', to: 'favorites#add_event_to_favorites'
    post 'add_recipe_to_favorites', to: 'favorites#add_recipe_to_favorites'



    
    #route for placement
    get 'competizioni', to: 'competizione#index'
    get 'competizione_create', to: 'competizione#create'
    
    # Rotte per le pagine della dashboard
    get 'dashboard', to: 'restaurateur_profiles#show'
    get 'info', to: 'info#show'
    get 'settings', to: 'settings#show'
  
    # rotte per le pagine vetrina
    get 'public_restaurant_profile/:id', to: 'restaurateur_profiles#public_show', as: 'public_restaurant_profile'
    get 'public_user_profile/:id', to: 'user_profile#public_show', as: 'public_user_profile'
    get 'public_critic_profile/:id', to: 'critic_profile#public_show', as: 'public_critic_profile'
    get 'public_show_menus/:id', to: 'menus#public_show', as: 'public_show_menus'
  
    # per i tag
    post 'restaurateur_profiles/:tag_id/add_tag', to: 'restaurateur_profiles#add_tag', as: 'add_tag'
    post 'restaurateur_profiles/:tag_id/remove_tag', to: 'restaurateur_profiles#remove_tag', as: 'remove_tag'
    
    # rotte per il login
    # Rotta per il form di login (GET e POST)
    get 'login', to: 'sessions#new', as: :user_login
    post 'login', to: 'sessions#create_user'
    
    # Rotta per il form di login del ristoratore (GET e POST)
    get 'login_restaurateur', to: 'sessions#new', as: :restaurateur_login
    post 'login_restaurateur', to: 'sessions#create_restaurateur'
    
    # Rotta per il logout (DELETE)
    delete 'logout', to: 'sessions#destroy', as: :logout
    #get 'sessions/new'
      
    get 'home/index'
    
  
    # rotte per la pagina di ricerca
    get 'ricerca', to: 'ricerca#index'
    get 'logout', to: 'sessions#destroy'
    get 'ricerca/:id/map_info', to: 'ricerca#map_info'

  
    get 'support', to: 'support#index'
    
    resources :promotions, only: [:index]
    resources :competizioni, only: [:index]
    resource :restaurateur_profiles, only: [:show, :edit, :update] do
      post 'create_event', to: 'restaurateur_profiles#create_event'
      delete 'destroy_event/:id', to: 'restaurateur_profiles#destroy_event', as: 'destroy_event'
      post 'create_recipe', to: 'restaurateur_profiles#create_recipe'
      delete 'destroy_recipe/:id', to: 'restaurateur_profiles#destroy_recipe', as: 'destroy_recipe'
      post 'add_tag/:tag_id', to: 'restaurateur_profiles#add_tag'
      delete 'destroy_promotion/:id', to: 'restaurateur_profiles#destroy_promotion', as: 'destroy_promotion'
  
      post :create_promotion, on: :collection
  
      collection do
        patch 'update_info', to: 'restaurateur_profiles#update_info'
      end
    end
  
    resource :user_profile, only: [:show, :edit, :update] do
      put 'update', on: :member
    end

    resource :critic_profile, only: [:show, :edit, :update] do
      put 'update', on: :member
    end

    resource :menus
    resources :piattos, only: [:new, :create, :destroy]
  
    resource :settings, only: [:show, :edit, :update, :destroy]
    put 'update_credentials', to: 'settings#update_credentials'
    post 'verify_password', to: 'settings#verify_password'
    resources :eventi, only: [:create]
    resources :info, only: [:show] 
  
    resource :segnalaziones, only: [:create]
    get 'segnalazione_index', to: 'segnalaziones#index'
    delete 'segnalzaione_delete', to: 'segnalaziones#destroy'

    
    # Rotte aggiunte per creare e distruggere un dipendente
    post 'info/create_dipendente', to: 'info#create_dipendente', as: 'create_dipendente'
    delete 'info/destroy_dipendente/:id', to: 'info#destroy_dipendente', as: 'destroy_dipendente'

    #rotte per le risposte dei ristoratori
    post 'answer_create', to: 'answer#create'
    post 'answer_update', to: 'answer#update'
    delete 'answer_delete', to: 'answer#destroy'
  
    post 'update_review', to: 'reviews#update'
    #rotta per le recensioni
    resources :reviews, only: [:create, :destroy] do
      member do
        post 'add_like'
      end
    end

    # AUTHENTICATION ROUTES 
    get 'auth/:provider/callback', to: 'sessions#create' 
    get '/sign_out', to: 'sessions#destroy', as: :sign_out 
    get '/auth/google_oauth2', as: :sign_in
    get '/auth/failure' => 'sessions#failure'
  end

foodadvisor/app/controllers/restaurateur_profiles_controller.rb
class RestaurateurProfilesController < ApplicationController 
  layout :determine_layout
  
  before_action :require_logged_in, except: [:public_show]
  before_action :require_restaurant_owner, except: [:public_show]
  before_action :set_restaurant_owner
  before_action :set_evento, only: [:destroy_event] 

  def show
    @eventi = Evento.where(ristoratore_id: @restaurant_owner.cliente.ristoratore.id).where("data >=?", Date.today)
    @promotions = @restaurant_owner.cliente.ristoratore.promotions
    @tags = @restaurant_owner.cliente.ristoratore.tags
    @recipes = @restaurant_owner.cliente.ristoratore.recipes
    @reviews=Recensione.includes(cliente: :user).where(ristoratore_id: @restaurant_owner.cliente.ristoratore.id)
  end

  def edit
    load_associated_data # Carica di nuovo i dati associati per la vista edit
  end

  def add_tag
    @tag = Tag.find(params[:tag_id])
    if @restaurant_owner.cliente.ristoratore.tags.exclude?(@tag)
      @restaurant_owner.cliente.ristoratore.tags << @tag
      flash[:success] = "Tag aggiunto con successo."
    else
      flash[:error] = "Il tag è già associato al ristoratore."
    end
    redirect_to edit_restaurateur_profiles_path  # Reindirizza alla pagina di modifica del profilo
  end

  def remove_tag
    @tag = Tag.find(params[:tag_id])
    if @restaurant_owner.cliente.ristoratore.tags.include?(@tag)
      @restaurant_owner.cliente.ristoratore.tags.delete(@tag)
      flash[:success] = "Tag rimosso con successo."
    else
      flash[:error] = "Il tag non è associato al ristoratore."
    end
    redirect_to edit_restaurateur_profiles_path  # Reindirizza alla pagina di modifica del profilo
  end

  def update_info
    puts "PARAMETRI: #{restaurant_owner_new_params.inspect}" # Debug output
    if @restaurant_owner.update(restaurant_owner_new_params)
      redirect_to edit_restaurateur_profiles_path, notice: 'Profilo aggiornato con successo.'
    else
      load_associated_data # Carica di nuovo i dati associati per la vista edit
      render :edit
    end
  end

  def create_event
    locandina_path = save_locandina(params[:locandina]) if params[:locandina].present?
  
    # Converte la stringa di data in un oggetto Date
    event_data = Date.parse(params[:data])
  
    @evento = Evento.new(
      ristoratore_id: @restaurant_owner.cliente.ristoratore.id,
      nome: params[:nome],
      data: event_data,
      luogo: params[:luogo],
      descrizione: params[:descrizione],
      locandina: locandina_path
    )
  
    if @evento.save
      redirect_to edit_restaurateur_profiles_path, notice: 'Evento creato con successo.'
    else
      redirect_to edit_restaurateur_profiles_path, alert: 'Errore nella creazione dell\'evento.'
    end
  rescue ArgumentError => e
    redirect_to edit_restaurateur_profiles_path, alert: "Errore nella data dell'evento: #{e.message}"
  end
  

  def create_promotion
    @promotion = Promotion.new(
      ristoratore_id: @restaurant_owner.cliente.ristoratore.id,
      data_inizio: params[:data_inizio],
      data_fine: params[:data_fine],
      condizioni: params[:condizioni],
      tipo: params[:tipo]
    )

    if @promotion.save
      redirect_to edit_restaurateur_profiles_path, notice: 'Promozione creata con successo.'
    else
      redirect_to edit_restaurateur_profiles_path, alert: 'Errore nella creazione della promozione.'
    end
  end

  def create_recipe
    photo_path = save_locandina(params[:photo]) if params[:photo].present?
  
    @recipe = Recipe.new(
      ristoratore_id: @restaurant_owner.cliente.ristoratore.id,
      name: params[:name],
      difficulty: params[:difficulty],
      ingredients: params[:ingredients],
      procedure: params[:procedure],
      photo: photo_path
    )
  
    if @recipe.save
      redirect_to edit_restaurateur_profiles_path, notice: 'Ricetta creata con successo.'
    else
      redirect_to edit_restaurateur_profiles_path, alert: 'Errore nella creazione della ricetta.'
    end
  end

  def destroy_promotion
    @promotion = Promotion.find_by(id: params[:id])

    if @promotion
      if @promotion.destroy
        render json: { success: true }, status: :ok
      else
        render json: { success: false, error: 'Errore durante l\'eliminazione della promozione' }, status: :unprocessable_entity
      end
    else
      render json: { success: false, error: 'Promozione non trovata' }, status: :not_found
    end
  end

  def destroy_recipe
    @recipe = Recipe.find_by(id: params[:id])

    if @recipe
      @recipe.destroy
      render json: { success: true }
    else
      render json: { success: false, error: 'Non sei autorizzato a eliminare questa ricetta.' }, status: :forbidden
    end
  rescue StandardError => e
    render json: { success: false, error: e.message }, status: :unprocessable_entity
  end

  def destroy_event
    if @evento.ristoratore_id == @restaurant_owner.cliente.ristoratore.id
      @evento.destroy
      render json: { success: true }
    else
      render json: { success: false, error: 'Non sei autorizzato a eliminare questo evento.' }, status: :forbidden
    end
  rescue StandardError => e
    render json: { success: false, error: e.message }, status: :unprocessable_entity
  end

  def update_pin
    @review = Recensione.find(params[:review_id])

    if @review.pinnata
      flash[:alert] = 'La recensione è già pinnata.'
    else
      @review.update(pinnata: true)
      flash[:notice] = 'Recensione pin successfully updated.'
    end

    redirect_back(fallback_location: restaurateur_profiles_path)
  end

  # Nuova azione pubblica per mostrare il profilo vetrina
  def public_show
    @restaurant_owner = Ristoratore.find(params[:id])
    @eventi = Evento.where(ristoratore_id: @restaurant_owner.cliente.ristoratore.id).where("data >= ?", Date.today)
    @promotions = Promotion.where(ristoratore_id: @restaurant_owner.cliente.ristoratore.id)
    @tags = @restaurant_owner.cliente.ristoratore.tags
    @recipes = @restaurant_owner.cliente.ristoratore.recipes
    @reviews=Recensione.includes(cliente: :user).where(ristoratore_id: @restaurant_owner.cliente.ristoratore.id).order(pinnata: :desc)

    if params[:date].present?
      @reviews = @reviews.where("DATE(created_at) = ?", params[:date])
    end

    if params[:stars_from].present?
      @reviews = @reviews.where("stelle >= ?", params[:stars_from])
    end

    if params[:stars_to].present?
      @reviews = @reviews.where("stelle <= ?", params[:stars_to])
    end

    if params[:order].present?
      order = params[:order] == 'asc' ? 'ASC' : 'DESC'
      @reviews = @reviews.order("created_at #{order}")
    end

  end

  private

  def require_logged_in
    unless logged_in?
      redirect_to login_path
    end
  end

  def require_restaurant_owner
    unless session[:role] == 'Ristoratore'
      redirect_to root_path
    end
  end

  def set_restaurant_owner
    @restaurant_owner = @current_user
  end

  def set_evento
    @evento = Evento.find(params[:id])
  end

  def restaurant_owner_params
    params.require(:ristoratori).permit(:restaurant_name, :email, :phone, :photo)
  end

  def restaurant_owner_new_params
    params.require(:ristoratori).permit(:restaurant_name, :indirizzo, :email, :phone)
  end

  def determine_layout
    action_name == 'public_show' ? 'application' : 'with_sidebar'
  end

  def load_associated_data
    @eventi = Evento.where(ristoratore_id: @restaurant_owner.cliente.ristoratore.id).where("data > ?", Date.today)
    @promotions = Promotion.where(ristoratore_id: @restaurant_owner.cliente.ristoratore.id)
    @tags = @restaurant_owner.cliente.ristoratore.tags
    @categories = Tag.distinct.pluck(:categoria)
    @recipes = @restaurant_owner.cliente.ristoratore.recipes
  end

  # Metodo per salvare l'immagine in assets/images e restituire il percorso
  def save_locandina(image)
    # Genera un nome univoco per l'immagine
    filename = "#{SecureRandom.hex(8)}_#{image.original_filename}"
    # Percorso completo di salvataggio
    directory = Rails.root.join('app', 'assets', 'images')
    path = File.join(directory, filename)
    # Salva il file nell'immagine
    File.open(path, 'wb') do |file|
      file.write(image.read)
    end
    # Restituisce il percorso relativo dell'immagine
    "/assets/#{filename}"
  end
end

foodadvisor/app/views/restaurateur_profiles/edit.html.erb
<%= javascript_include_tag 'rest_edit', 'data-turbolinks-track': 'reload' %>

<%= link_to 'Salva', rest_profile_path, class: 'linksito' %>

<% if flash[:notice] %>
    <div class="alert alert-success" role="alert">
      <%= flash[:notice] %>
    </div>
  <% end %>

  <% if flash[:alert] %>
    <div class="alert alert-danger" role="alert">
      <%= flash[:alert] %>
    </div>
  <% end %>
<h3>Tags</h3>
<div class="r-statistiche">
  <div class="r-stat">
    <div class="r-tags">
      <% if @tags.present? %>
        <% @tags.each do |tag| %>
          <% category_class = tag.categoria.downcase.gsub(' ', '-') %>
          <span class="piatto category-<%= category_class %>"><%= tag.nome %></span>
        <% end %>
      <% end %>
      <table>
        <% @categories.each do |category| %>
          <tr class="<%= category.downcase.gsub(' ', '-') %>">
            <td class="category-header"><%= category %></td>
            <td class="dish-container">
              <% tags = Tag.where(categoria: category) %>
              <% tags.each do |tag| %>
                <div class="piatto">
                  <%= tag.nome %>
                  <% if @tags.include?(tag) %>
                    <%= form_with url: remove_tag_path(tag_id: tag.id), method: :post, class: 'inline-form' do %>
                      <%= hidden_field_tag :tag_id, tag.id %>
                      <%= hidden_field_tag :action_type, 'remove' %>
                      <button type="submit" class="button-with-icon">
                        <i class="fas fa-times"></i>
                      </button>
                    <% end %>
                  <% else %>
                    <%= form_with url: add_tag_path(tag_id: tag.id), method: :post, class: 'inline-form' do %>
                      <%= hidden_field_tag :tag_id, tag.id %>
                      <%= hidden_field_tag :action_type, 'add' %>
                      <button type="submit" class="button-with-icon">
                        <i class="fas fa-plus"></i>
                      </button>
                    <% end %>
                  <% end %>
                </div>
              <% end %>
            </td>
          </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>



<h3>Promozioni</h3>
<div class="r-promozioni">
  <div class="promo-grid">
    <% if @promotions.present? %>
      <% @promotions.each do |promotion| %>
        <div class="promo-box" id="promotion-<%= promotion.id %>">
          <p style="font-weight: bold;">Tipo Promozione: <span style="font-weight: normal;"><%= promotion.tipo %></span></p>
          <p style="font-weight: bold;">Data Inizio: <span style="font-weight: normal;"><%= promotion.data_inizio %></span></p>
          <p style="font-weight: bold;">Data Fine: <span style="font-weight: normal;"><%= promotion.data_fine %></span></p>
          <p style="font-weight: bold;">Condizioni: <span style="font-weight: normal;"><%= promotion.condizioni %></span></p>
          <ion-icon name="close-circle-outline" class="del-promo-icon" id="del-promo-icon" data-promotion-id="<%= promotion.id %>" style="font-size: 25px; cursor: pointer;"></ion-icon>

        </div>
        <div class="vertical-divider" style="height: 100px;"></div>
      <% end %>
    <% else %>
      <p>Nessuna promozione attiva</p>
    <% end %>
  </div>
</div>
<button type="button" id="add-promo-btn">Aggiungi Promozione</button>

<h3>Ricette Condivise</h3>
<div class="r-ricette">
  <% if @recipes.any? %>
    <% @recipes.each do |recipe| %>
      <div class="r-ricetta" id="recipe-<%= recipe.id %>">
        <% if recipe.photo.present? %>
          <%= image_tag recipe.photo, class: 'ricetta-foto' %>
        <% else %>
          <%= image_tag 'background.jpg', class: 'ricetta-foto' %>
        <% end %>
        <div class="ricetta-info">
          <p>Nome: <%= recipe.name %></p>
          <p>Difficoltà: <%= recipe.difficulty %></p>
          <p>Ingredienti: <%= recipe.ingredients %></p>
          <p>Procedimento: <%= recipe.procedure %></p>
        </div>
        <i class="fa fa-trash delete-recipe-icon" data-recipe-id="<%= recipe.id %>" style="font-size: 15px; cursor: pointer;"></i>
      </div>
    <% end %>
  <% else %>
    <p>Il ristoratore non ha condiviso alcuna ricetta.</p>
  <% end %>
</div>
<button type="button" id="add-recipe-btn">Aggiungi Ricetta</button>

<h3>Eventi</h3>
<div class="r-eventi">
  <% if @eventi.any? %>
    <% @eventi.each do |evento| %>
      <div class="r-evento" id="evento-<%= evento.id %>">
        <% if evento.locandina.present? %>
          <%= image_tag evento.locandina, class: 'evento-foto'  %>
        <% else %>
          <%= image_tag 'background.jpg', class: 'evento-foto' %>
        <% end %>
        <div class="evento-info">
          <p><%= evento.nome %></p>
          <p>Data: <%= evento.data %></p>
          <p>Luogo: <%= evento.luogo %></p>
          <p>Desc: <%= evento.descrizione %></p>
        </div>
        <i class="fa fa-trash delete-icon" data-event-id="<%= evento.id %>" style="font-size: 15px; cursor: pointer;"></i>
      </div>
    <% end %>
  <% else %>
    <p>Il ristoratore non ha creato alcun evento.</p>
  <% end %>
</div>
<button type="button" id="add-event-btn">Aggiungi Evento</button>

<!-- Finestra modale creazione evento -->
<div id="myModal" class="modal">
  <div class="modal-content">
    <span class="close">&times;</span>
    <h2>Crea Nuovo Evento</h2>
    <%= form_with(url: create_event_restaurateur_profiles_path, method: :post, local: true) do |form| %>
      <div>
        <%= form.label :nome, "Nome Evento" %>
        <%= form.text_field :nome, class: "form-control" %>
      </div>
      <div>
        <%= form.label :data, "Data Evento" %>
        <%= form.date_field :data, id: "eventDate", class: "form-control" %>
      </div>
      <div>
        <%= form.label :luogo, "Luogo Evento" %>
        <%= form.text_field :luogo, class: "form-control" %>
      </div>
      <div>
        <%= form.label :descrizione, "Descrizione Evento" %>
        <%= form.text_area :descrizione, class: "form-control" %>
      </div>
      <div>
        <%= form.label :locandina, "Locandina Evento" %>
        <%= form.file_field :locandina, class: "form-control" %>
      </div>
      <div>
        <%= form.submit "Crea Evento", class: "btn btn-primary" %>
        <button type="button" id="resetBtn">Azzera</button>
      </div>
    <% end %>
  </div>
</div>


<!-- finestra modale creazione promozioni -->
<div id="myModal2" class="modal">
  <div class="modal-content">
    <span class="close" id="close-promo-modal">&times;</span>
    <h2>Aggiungi Promozione</h2>
    <%= form_with(url: create_promotion_restaurateur_profiles_path, method: :post, local: true) do |form| %>
      <div class="form-group">
        <%= form.label :tipo, "Tipo Promozione" %>
        <%= form.text_field :tipo, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= form.label :data_inizio, "Data Inizio" %>
        <%= form.date_field :data_inizio, class: "form-control", id: "eventDatePromo" %>
      </div>
      <div class="form-group">
        <%= form.label :data_fine, "Data Fine" %>
        <%= form.date_field :data_fine, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= form.label :condizioni, "Condizioni" %>
        <%= form.text_area :condizioni, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= form.submit "Salva Promozione", class: "btn btn-primary" %>
        <button type="button" id="resetBtnPromo">Azzera</button>
      </div>
    <% end %>
  </div>
</div>


<!-- Finestra modale creazione ricette -->
<div id="myModal3" class="modal">
  <div class="modal-content">
    <span class="close" id="close-recipe-modal">&times;</span>
    <h2>Aggiungi Ricetta</h2>
    <%= form_with(url: create_recipe_restaurateur_profiles_path, method: :post, local: true) do |form| %>
      <div class="form-group">
        <%= form.label :photo, "Foto ricetta" %>
        <%= form.file_field :photo %>
      </div>
      <div class="form-group">
        <%= form.label :name, "Nome" %>
        <%= form.text_field :name, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= form.label :difficulty, "Difficoltà" %>
        <%= form.text_field :difficulty, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= form.label :ingredients, "Ingredienti" %>
        <%= form.text_field :ingredients, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= form.label :procedure, "Procedimento" %>
        <%= form.text_field :procedure, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= form.submit "Salva Ricetta", class: "btn btn-primary" %>
        <button type="button" id="resetBtnRecipe">Azzera</button>
      </div>
    <% end %>
  </div>
</div>

<!-- Finestra di conferma eliminazione evento -->
<div id="confirmModal" class="modal">s
  <div class="modal-content">
    <span class="close-confirm">&times;</span>
    <h2>Conferma Eliminazione</h2>
    <p>Sei sicuro di voler eliminare questo evento?</p>
    <button id="confirmDeleteBtn">Conferma</button>
    <button id="cancelDeleteBtn">Annulla</button>
  </div>
</div>

<!-- Finestra di conferma eliminazione promozione -->
<div id="confirmModalPromo" class="modal">s
  <div class="modal-content">
    <span class="close-confirm-promo">&times;</span>
    <h2>Conferma Eliminazione</h2>
    <p>Sei sicuro di voler eliminare questo evento?</p>
    <button id="confirmDeleteBtnPromo">Conferma</button>
    <button id="cancelDeleteBtnPromo">Annulla</button>
  </div>
</div>

<!-- Finestra di conferma eliminazione ricetta -->
<div id="confirmModalRecipe" class="modal">s
  <div class="modal-content">
    <span class="close-confirm-recipe">&times;</span>
    <h2>Conferma Eliminazione</h2>
    <p>Sei sicuro di voler eliminare questo evento?</p>
    <button id="confirmDeleteBtnRecipe">Conferma</button>
    <button id="cancelDeleteBtnRecipe">Annulla</button>
  </div>
</div>